"use client";

/**
 * The shared panel every AI screen is built from.
 *
 * One component, five features, because they all have the same shape:
 * a form, a spinner, an error, and a result that must be shown alongside its
 * assumptions.
 *
 * The assumptions block is not decoration. The PRD forbids presenting AI
 * output as fact, and a wall of confident advice with no visible caveats is
 * exactly how that gets violated in practice. `children` receives the data;
 * the assumptions and the not-researched warning are rendered here so no
 * feature can forget them.
 */

import { useState, type ReactNode } from "react";
import type { AiResult } from "@/lib/ai/provider";
import type { AiActionResult } from "@/lib/ai/actions";

export type Allowance = {
  configured: boolean;
  used: number;
  cap: number;
  remaining: number;
};

function ConfigureKey() {
  return (
    <div className="rounded-xl border border-warning/40 bg-warning/10 p-5">
      <h2 className="text-sm font-bold">The AI studio needs an API key</h2>
      <p className="mt-2 max-w-prose text-sm text-muted">
        The code is ready. What is missing is a key for a large language model
        provider, and which provider to use has not been decided yet — it is
        open question 1 in{" "}
        <code className="font-mono text-xs">docs/DECISIONS.md</code>.
      </p>
      <p className="mt-3 text-sm">
        Add{" "}
        <code className="rounded bg-surface-2 px-1.5 py-0.5 font-mono text-xs">
          AI_API_KEY
        </code>{" "}
        to <code className="font-mono text-xs">.env.local</code>, then restart
        the server.
      </p>
      <p className="mt-3 text-sm text-muted">
        Everything else works without it. Products, customers, orders and
        finance are all live right now.
      </p>
    </div>
  );
}

function AllowanceBar({ allowance }: { allowance: Allowance }) {
  if (!allowance.configured) return null;
  if (allowance.cap <= 0) return null;

  const pct = Math.min(100, (allowance.used / allowance.cap) * 100);
  const low = allowance.remaining <= 5;

  return (
    <div className="rounded-lg border border-border bg-surface px-4 py-2.5">
      <div className="flex items-center justify-between text-xs">
        <span className="font-semibold text-muted">AI requests today</span>
        <span className={low ? "font-bold text-warning" : "text-muted"}>
          {allowance.used} of {allowance.cap} used
        </span>
      </div>
      <div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-surface-2">
        <div
          className={`h-full rounded-full ${low ? "bg-warning" : "bg-brand"}`}
          style={{ width: `${Math.max(pct, allowance.used > 0 ? 3 : 0)}%` }}
        />
      </div>
    </div>
  );
}

/**
 * Assumptions and warnings, rendered above any AI output.
 *
 * Deliberately above the content, not below it. Someone who scrolls past
 * caveats has already acted on the advice.
 */
function Provenance({ result }: { result: AiResult<unknown> }) {
  return (
    <div className="mb-5 space-y-3">
      <div className="rounded-lg border border-warning/40 bg-warning/10 px-4 py-3">
        <p className="text-xs font-bold uppercase tracking-wide text-warning">
          AI advice, not research
        </p>
        <p className="mt-1 text-xs text-muted">
          Generated by {result.model}. Nobody has checked it. Treat every figure
          as a starting point to verify, not a finding.
        </p>
      </div>

      {result.assumptions.length > 0 && (
        <div className="rounded-lg border border-border bg-surface-2 px-4 py-3">
          <p className="text-xs font-bold">What this assumed</p>
          <ul className="mt-1.5 space-y-1">
            {result.assumptions.map((a, i) => (
              <li key={i} className="text-xs text-muted">
                · {a}
              </li>
            ))}
          </ul>
        </div>
      )}

      {result.warnings.length > 0 && (
        <div className="rounded-lg border border-danger/30 bg-danger/5 px-4 py-3">
          <p className="text-xs font-bold text-danger">Before you rely on this</p>
          <ul className="mt-1.5 space-y-1">
            {result.warnings.map((w, i) => (
              <li key={i} className="text-xs text-muted">
                · {w}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

/** Passed to the feature screen so its button can trigger a call. */
export type AiRunner<T> = (call: () => Promise<AiActionResult<T>>) => Promise<void>;

export function AiPanel<T>({
  allowance,
  /** The input form, given the runner so its button can call the action. */
  form,
  /** Renders the result. Only called when there is one. */
  children,
  /** Optional right-hand column, e.g. recent generations. */
  aside,
}: {
  allowance: Allowance;
  form: (run: AiRunner<T>) => ReactNode;
  children?: (data: T, result: AiResult<T>) => ReactNode;
  aside?: ReactNode;
}) {
  const [result, setResult] = useState<AiActionResult<T> | null>(null);
  const [busy, setBusy] = useState(false);

  const run: AiRunner<T> = async (call) => {
    setBusy(true);
    try {
      setResult(await call());
    } finally {
      setBusy(false);
    }
  };

  if (!allowance.configured) {
    return <ConfigureKey />;
  }

  return (
    <div className="space-y-5">
      <AllowanceBar allowance={allowance} />

      {aside && <div>{aside}</div>}

      {form(run)}

      {result?.status === "error" && (
        <div
          role="alert"
          className="rounded-xl border border-danger/40 bg-danger/10 px-4 py-3"
        >
          <p className="text-sm font-semibold text-danger">{result.message}</p>
          {result.code === "invalid_response" && (
            <p className="mt-1.5 text-xs text-muted">
              This is the app refusing to show a response it could not verify. It
              is deliberate: advice with no stated assumptions must not look
              like a finding.
            </p>
          )}
          {result.code === "daily_cap" && (
            <p className="mt-1.5 text-xs text-muted">
              The limit exists so a single user cannot spend the whole AI budget.
            </p>
          )}
        </div>
      )}

      {busy && (
        <div className="rounded-xl border border-border bg-surface p-8 text-center" role="status">
          <p className="text-sm font-semibold">Thinking…</p>
          <p className="mt-1 text-xs text-muted">
            This usually takes 10 to 30 seconds.
          </p>
        </div>
      )}

      {result?.status === "ok" && children && (
        <div className="rounded-xl border border-border bg-surface p-5">
          <Provenance result={result.data} />
          {children(result.data.content, result.data)}
        </div>
      )}
    </div>
  );
}

/**
 * The button every feature screen uses.
 *
 * Owns its own busy state as well as the panel's, so the label can change
 * ("Generating…") rather than just the control disabling. Two sources of
 * truth for one flag would eventually disagree.
 */
export function GenerateButton<T>({
  run,
  call,
  label,
  busyLabel,
  disabled,
}: {
  run: AiRunner<T>;
  call: () => Promise<AiActionResult<T>>;
  label: string;
  busyLabel: string;
  disabled?: boolean;
}) {
  const [busy, setBusy] = useState(false);

  return (
    <button
      type="button"
      className="btn btn-primary"
      disabled={busy || disabled}
      onClick={async () => {
        setBusy(true);
        try {
          await run(call);
        } finally {
          setBusy(false);
        }
      }}
    >
      {busy ? busyLabel : label}
    </button>
  );
}
